### PR TITLE
Add configurable readiness & liveness probe

### PR DESCRIPTION
**Pull request by 0xF0D0**
Current k6 controller use default value of readiness & liveness probe.

In my case, this time slice is somewhat short and leads to readiness failure.

Through this pr, it can be configurable by k6 object

### CODE REVIEW

**Comment by yorugac** [comment]
Hi @0xF0D0, thanks for the PR! I agree that the probes are rather simplistic now and should be improved. Passing the configured probes seems like one way to do that. But could you please clarify here:

> In my case, this time slice is somewhat short and leads to readiness failure.

what do you mean by the "time slice"?

**Comment by 0xF0D0** [comment]
I meant default readiness probe's `periodSeconds` and  `timeoutSeconds` are too small for my k6 workload

**Review by yorugac — CHANGES_REQUESTED** [review]
@0xF0D0 I have a small change request to improve readability - please check it out. Otherwise, LGTM!

**Review by yorugac — APPROVED** [review]
Thanks for the update!

**Pull request merged**
