### PR TITLE
Add initcontainer support for runners and intializer jobs

### LINKED ISSUE #118: init container
hi,

i searched the crd and code and found out that the operator dosent have an option for an "initContainer".
i would like to know if you can add it in the next update/release.

### PR DESCRIPTION
**Pull request by andrei-trandafir**
Closes #118

I know there's already a pull request in progress (https://github.com/grafana/k6-operator/pull/184), but it hasn't seen any activity for ~4months

### CODE REVIEW

**Comment by yorugac** [comment]
Hello @andrei-trandafir, Thanks for opening this. Actually PR #184 was updated just ~ 3 weeks ago [here](https://github.com/grafana/k6-operator/pull/184/commits/897b980ccee00e4486bd71faf4560d137383fb14) :sweat_smile: 

I believe we all want to have the init containers merged quickly, but it seems you haven't preserved the commits from that PR? I think its preferable to do that in case when you're building on top of others' work. 

Additionally, I've received communication from Ivan that he wishes to come back to that PR in ~ July: I should have written it in public probably :disappointed: Let me ping him over there too: and please subscribe to that PR if you haven't yet.

**Comment by andrei-trandafir** [comment]
Thanks for the update @yorugac 
I created the fork from the latest k6-operator commit in order to avoid merge conflicts and didn’t have write access to the other PR’s fork.

I’ll keep an eye out on the other PR

**Comment by andrei-trandafir** [comment]
Thanks for the update @yorugac 
I created the fork from the latest k6-operator commit in order to avoid merge conflicts and didn’t have write access to the other PR’s fork.

I’ll keep an eye out on the other PR

**Comment by yorugac** [comment]
Hi @andrei-trandafir, my apologies for the mess around this but init containers were just merged. And now also built and available as [this image here](https://github.com/grafana/k6-operator/pkgs/container/operator/103697347?tag=b7ba1ba0a53263a23eda01e8be3aa1203562493e). Please try it out and let us know if something is off!
I'm closing this PR now; please feel free to open a new one if some fix is needed.

**Pull request closed without merging**
