### PR TITLE
feat: Add Helm configuration for container security context

### LINKED ISSUE #377: Helm Chart Install with hashicorp/helm_release provider can't find k6-operator chart
### Brief summary

I am trying to install the k6-operator helm chart with terraform hashicorp/helm_release provider.  I have tried to reference the repository via OCI/https and the provider cannot find the chart. Please provide the url and chart to put in the helm_release resource.

### k6-operator version or image

0.0.13

### Helm chart version (if applicable)

3.5.0

### TestRun / PrivateLoadZone YAML

NA

### Other environment details (if applicable)

_No response_

### Steps to reproduce the problem

Create a terraform resource below.
```
resource "helm_release" "k6_operator" {
  name             = "k6-operator"
  repository       = "https://grafana.github.io/helm-charts"
  chart            = "grafana/k6-operator"
  namespace        = "k6-operator-system"
  version          = "3.5.0" # var.operator_versions.chart_version
  create_namespace = false
  cleanup_on_fail  = true
  recreate_pods    = true
  wait             = true
}
```

### Expected behaviour

The provider can download the helm chart and install it. 

### Actual behaviour

Getting error when installing helm chart. 
```
module.k6-operator.helm_release.k6_operator: Creating...
╷
│ Error: could not download chart: chart "grafana/k6-operator" version "3.5.0" not found in https://grafana.github.io/helm-charts repository
│
│   with module.k6-operator.helm_release.k6_operator,
│   on ..\modules\k6-operator\k6-operator.tf line 1, in resource "helm_release" "k6_operator":
│    1: resource "helm_release" "k6_operator" {
│
╵
```

### PR DESCRIPTION
**Pull request by gonmmarques**
Hello there,

Saw this issue https://github.com/grafana/k6-operator/issues/402 marked as good first issue and decided to give it a try.

Tried to follow a contributing guide, but only found https://github.com/grafana/k6-operator/issues/330.

Anyways, let me know if I missed something or is something wrong.

The way it is now added, by default the fields are optional for both of the containers in the deployment, but someone can change it in the Helm installation by setting the values e.g for manager container below:

```
manager:
  # ...
  # manager.containerSecurityContext -- A security context defines privileges and access control settings for the container.
  containerSecurityContext: {
    "runAsNonRoot": true,
    "runAsUser": 1000,
    "runAsGroup": 1000,
    "allowPrivilegeEscalation": false,
    "seccompProfile": {
      "type": "RuntimeDefault"
    },
    "capabilities": {
      "drop": [
        "ALL"
      ]
    }
  }

```  

Checked it by running locally the helm template and it rendered 
```
    spec:
      containers:
        - name: manager
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
```

Closes: #402

### CODE REVIEW

**Comment by yorugac** [comment]
Hi @gonmmarques, thanks for working on this!
The PR LGTM, the only thing left is to run `helm-docs` (_that_ will be in contributing guide for Helm additions).

However, I've just noticed that the [issue](https://github.com/grafana/k6-operator/issues/402) didn't specify whether it was about pod's `securityContext` or about container's `securityContext` :confused: For example `seccompProfile` is present in both.
I.e. it could be that container's one will not be sufficient for that case. @MohanedSaad, could you please clarify that bit?

**Comment by MohanedSaad** [comment]
> container's

Hi, thanks for picking this up. The container one should be enough for our case 😊

**Comment by gonmmarques** [comment]
Hello @yorugac 

Thanks for the feedback, however I did not find (as I mentioned) a Contributing guide, sorry if I missed something.
Can you please clarify if this means I should install this tool https://github.com/norwoodj/helm-docs and run it?

**Comment by yorugac** [comment]
Thanks for the update @gonmmarques and for feedback, @MohanedSaad!

**Review by yorugac — APPROVED** [review]

**Pull request merged**
