### PR TITLE
feat: use name instead of index for instance id tag

### PR DESCRIPTION
**Pull request by spoukke**
Currently,  the tag used for instance id is the index of the job. But, if you run multiple K6 resources at the same time, there is no way to distinguish them.

Here I propose to use the name of the job, instead of the index of the job

### CODE REVIEW

**Comment by yorugac** [comment]
Hi @spoukke,
Thanks for the PR and sorry for the delay! We cannot change `instance_id`: the whole point of `instance_id` tag is to distinguish between pods, not jobs. I suggest changing it to `job_name` tag instead and leaving `instance_id` as is. Would it work for your case?

**Comment by spoukke** [comment]
Yes, it would work, I am going to do the modification!

**Review by yorugac — APPROVED** [review]
LGTM :+1: Thank you @spoukke!

**Comment by yorugac** [comment]
But not the unit tests, apparently: https://github.com/grafana/k6-operator/runs/7917488949?check_suite_focus=true
They check the command and new tag is part of the command. Please check.

**Comment by spoukke** [comment]
Hi @yorugac ! Just updated the unit tests

**Review by yorugac — APPROVED** [review]
@spoukke Thanks for following up with this! Merging in now.

**Pull request merged**
